### ISSUE TITLE
Add validator to ensure IDs are unique

### ISSUE THREAD

**Issue by istvanrath** [FTSRG/mondo-collab-framework#13]
As the lens depends on model elements having unique IDs, we should make sure that both the offline and online editors, as well as the DSE Merge feature ensure that the models are valid in this sense.

I suggest to add an IncQuery validator and an additional Merge rule.

**Comment by bergmanngabor** [comment]
> As the lens depends on model elements having unique IDs

Minor clarifications:
 * IIRC the DSE merge also uses these unique IDs to establish correspondence between the different versions of the model.
 * As for the lens, the ID only plays a role in the offline scenario; but since it is needed there, it makes sense to enforce uniqueness in the online case as well, so I agree with István here.

**Comment by debrecenics** [comment]
In the online scenario, we automatically generate ID for new objects.

**Comment by debrecenics** [comment]
It is fixed in commit 8ac223eb7621472928f85e2f975ae702aee69660 from mondo-wt-demo repository.
